### ISSUE TITLE
Take Back The Web/Campus Campaign Page Template for Content

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/Community-Design#56]
## Goal: 
To have a template for static content on the takebacktheweb.mozilla.community site!

## Style Information: 
Please use the design from the rest of the website #35 

## Deadline: 
April 8th at the latest

## Tag: 
[Design Needed, Developer Needed, Question, Staff Support Needed]

**Comment by LucyeoH** [comment]
One potential idea for the template!! (Excuse my lack of design and/or drawing skills)

![image1 1](https://cloud.githubusercontent.com/assets/8070833/14257017/8f700424-fa69-11e5-969d-52f997c025d8.JPG)

**Comment by anistuhin** [comment]
Commenting for updates, will be working as developer when the graphics are done. @yofiesetiawan  and @elioqoshi a quick look on this will do I think, as they already got a the landing page, and @seeam might not be available for some days as he's having exams.

**Comment by tripad** [comment]
I am +1ing myself here for helping on the front-end code part of it.

**Comment by yofiesetiawan** [comment]
hi.. this is what i'm proposing... 

![05-cc-inside](https://cloud.githubusercontent.com/assets/2810823/14258015/b07f03b6-faca-11e5-8419-bcb5ac31628c.jpg)

**Comment by LucyeoH** [comment]
Hey @yofiesetiawan this is awesome and SO fast!!

Two initial thoughts: 
*  All the colours are cheerful but a bit distracting. I wonder if we could have the main background colour for the content be white, and then use one of the blues as a highlight box? 
*  What if the top two boxes are merged into one with overarching descriptor area and then the two bottom boxes stay separate so the screen wasn't split screen both vertically and horizontally?

Thanks again! 

Lucy

**Comment by yofiesetiawan** [comment]
hi, please check..
![06-cc-inside](https://cloud.githubusercontent.com/assets/2810823/14258943/e39fd122-face-11e5-8636-f42e11887331.jpg)

**Comment by Ryuno-Ki** [comment]
Commenting on https://github.com/mozilla/Community-Design/issues/56#issuecomment-205412526 - there's a "Subscribe"-Button in the right pane (above the participants) if you just comment to get notified on further comments, @tripad ;-)

**Comment by LucyeoH** [comment]
Hey Yofie! That's definitely closer! 

What if we kept the "hero" at the top small, like you had in your first one.

 And then put all three boxes against a white background. With a thing blue line dividing them? 

Trying to think of a way of making it a bit cleaner so the content can stand out and it can work for pages where we have a lot of writing ;) 

Lucy

**Comment by yofiesetiawan** [comment]
Hi Lucy, if you can share the text content you want to put there, i can better imagine how it should look...

**Comment by LucyeoH** [comment]
Hey Yofie! So this template needs to be useable for 6 pages (so we need to have lots of space for writing and pretty plain). 

1 page - for more info about the Campus Team Role
1 page - for more info about the Local Coach Role 
3 pages - 1 page each for the impact areas (x3) 
1 page - FAQ about Campus Campaign

**Comment by yofiesetiawan** [comment]
Can you also send the text content for example, page for Campus Team Role? You can write it and draw it on paper...

**Comment by LucyeoH** [comment]
Hey! [Here](https://wiki.mozilla.org/Participation/Campus-Campaign/Roles-and-Responsibilities) is some of the written content we'll be including in the page. 

![image1 2](https://cloud.githubusercontent.com/assets/8070833/14293291/f6296932-fb39-11e5-92c0-4df56f7bf807.JPG)

**Comment by LucyeoH** [comment]
My thought is that the top bit is the hero with the page title like you already have. And then the rest is white background with clean blue lines that don't go all the way across but just divide the space kind of minimally. 

Does that make sense? Sorry for being complicated!!

**Comment by yofiesetiawan** [comment]
Hi, 

Please check.. 
![07-cc-inside](https://cloud.githubusercontent.com/assets/2810823/14313410/b642486a-fc1b-11e5-8c9b-e8b05e190d99.jpg)

or
![08-cc-inside](https://cloud.githubusercontent.com/assets/2810823/14313608/ad523d72-fc1c-11e5-8e55-35a6ba0daa50.jpg)

**Comment by LucyeoH** [comment]
@yofiesetiawan these are BEAUTIFUL! I like the second one best. Can you send the files we need? Thank you! Thank you! Thank you!

**Comment by phinity** [comment]
Yofie, This is awesome! I have time next week to set this up on [the community site](https://takebacktheweb.mozilla.community). Here are some suggestions I think can improve on this general direction. It would be great to see some or all of this in photoshop design, if possible. 

General:
• The paragraph body copy font-size is set to 16px and line-height 24px for readability. This is what we ended up with on the homepage and we should be consistent.

Hero:  
• I think the headline should be vertically centered between the nav/tab and the bottom of hero. 
• Maybe just little taller?
• Word-case please, so just the first letter of each word that is capitalized. 
• The font weight looks different than the home, can we go with the same treatment on the homepage: Open Sans extra-bold, instead of just bold. 

Content area 1: "Roles & Responsibilities"
• The centered text treatment is nice but I think we’ll have more content that needs to be readable. Left aligned text that spans multiple paragraphs is important. This will also lend to "generic content" pages we may have on the site like a FAQ page and maybe even blog articles.

Content area 2: “Commitment” / "How to apply"
• The content1 area above and the footer below are both white so this area seems to not stand out enough. Can we try a light gray background instead of a border or maybe even color(s) from the hero for background color with white type? 
• Can we use the same rounded button treatment from the homepage for consistency. 

Thats it. Thanks so much for your awesome work here! I can add a note in the source for you. :]

**Comment by phinity** [comment]
@yofiesetiawan The one thing would be helpful to see in the design, if I had to pick one, is the updates to the Content area 2: “Commitment” / "How to apply"

**Comment by yofiesetiawan** [comment]
Hi,

Thanks @phinity for the clear guidelines. I managed to maintain the consistency. Please check.

![09-cc-inside](https://cloud.githubusercontent.com/assets/2810823/14405239/867fab18-feb4-11e5-9048-2aaebe0a1066.jpg)
Download PSD https://dl.dropboxusercontent.com/u/4450713/mozilla/GitHub/09-cc-inside.psd.zip
