### ISSUE TITLE
Video about RepsNext

### ISSUE THREAD

**Issue by nukeador** [mozilla/Community-Design#67]
## Goal: 
A video summarizing the interviews to Reps Council and Peers about the evolution of the program.

## Info: 
The raw interviews are [uploaded here](https://cloud.nukeador.com/index.php/s/8ZSGQyzsOsPVeWk). 

## Style Information: 
The idea is to merge the videos including the most interesting portions of the interviews and put together answers to a similar question and replace mi voice asking the questions with a (mozilla style)slide with the written question.

Intro (Mozilla Reps - An evolution to the program)
Question 1 slide
* Reply 1 portion
* Reply 2 portion
Question 2 slide
* Reply 1 portion
* Reply 2 portion

The sound is not perfect, so I don't know if it's possible to clean/reduce the background noise a bit.

## Deadline: 
It would be great to have it before London (June 13th)

## Tag: 
Video editing

**Comment by yofiesetiawan** [comment]
Hi,
What is Question 1 slide, Question 2 slide? How many minutes you like the video to be? Can you help to put the names of the people and their position (Reps Council, Reps, etc) that you like to be in the video?

**Comment by elioqoshi** [comment]
@nukeador can you provide the details @yofiesetiawan asked about?

**Comment by nukeador** [comment]
Hey sorry, I'm in the middle of a lot of stuff.

Video should be no longer than 3 minutes I think, in order for people to actually play it, I don't know what you think.

Questions slides should be the same questions I asked in the videos (we don't need to include everything, just the parts that feel more relevant)

These are the people inside Council and Peers:
* https://reps.mozilla.org/people/#/group/council/
* https://wiki.mozilla.org/Modules/Mozilla_Reps

Since I won't have a lot of time during the next 15 days to check on this, I think you should be free to innovate here, I don't want to limit your creativity with very detailed instructions on how everything should look like but more the overall idea of what we want to accomplish. I trust your judgment and creativity ;)

**Comment by yofiesetiawan** [comment]
Hi,
It's quite difficult to make it as a short video, since most of the people here speak with tones that are not easy to cut off. I'm trying my best to make it as short as possible, these are 2 versions of the long and short video...

Short (4:06)
https://www.youtube.com/watch?v=Y6eTHftRczI

Long (10:09)
https://www.youtube.com/watch?v=Jd5JhB2Sc4k

**Comment by MichaelKohler** [comment]
Amazing work, thanks! This will be great, if we can make a few improvements. The length is perfect I think. Here’s my full feedback:

There are some really minor grammatical changes I’d suggest:

Short:
0:18  How will the Reps program CHANGE?
2:59  How is RepsNext helping LOCAL COMMUNITIES?
3:24  (tricky one because of the orange word pattern, I guess we need to break the “always noun”) What EXCITES you about RepsNext?

Long:
1:02   How will the Reps program CHANGE?
5:27   Why do we need CHANGES?
6:44    How is RepsNext helping LOCAL COMMUNITIES?
8:12  (tricky one because of the orange word pattern, I guess we need to break the “always noun”) What EXCITES you about RepsNext?

And as Elio mentioned in the Design telegram group, it would be nice to turn down the music a little bit during the interviews. 

Apart from this I think it’s great, so much appreciated and amazing work!

**Comment by nukeador** [comment]
@yofiesetiawan the short version is GREAT, it captures a good summary :D

+1 to @MichaelKohler suggestions.

**Comment by yofiesetiawan** [comment]
This is the edited version as requested by @MichaelKohler 
https://www.youtube.com/watch?v=P0CCtQNwW4o

**Comment by yofiesetiawan** [comment]
Here is the link to short video with better resolution 720p https://www.youtube.com/watch?v=FpQYyAcG8AU

**Comment by MichaelKohler** [comment]
Thanks Yofie, this is amazing!

**Comment by elioqoshi** [comment]
Thanks Yofie, much appreciated! Closing this :)
